### ISSUE TITLE
v0.1.7 release not in Github repo

### ISSUE THREAD

**Issue by patrick-fitzgerald** [jpopesculian/twitter-v2-rs#13] opened 2022-10-04 23:28 UTC
Hi, 

I had a question about [v0.1.7](https://crates.io/crates/twitter-v2/0.1.7 ) on crates.io as I don't see the [v0.1.7](https://github.com/jpopesculian/twitter-v2-rs/tags) tag on Github.
Does it need to be pushed to the repo? I wanted to check before using the latest version.

Thanks,
Patrick

**Comment by jpopesculian** [comment] 2022-10-25 14:59
I'm gonna be honest, I don't know how they got misaligned but I just diffed what's on crates.io to the repo and they're the same, so it seems to be a duplicate of 0.1.6. In any case, I'm gonna publish v0.1.8 and make sure its tagged!

**Closed by jpopesculian** 2022-10-25 14:59 UTC
